### ISSUE TITLE
bruh gee man attack helicoper doesnt work

### ISSUE THREAD

**Issue by iamthesenate-69** [dthusian/sasuke-prism#1]
"Go! Launch the attack helicopters against @imanity go online nerd" doesnt work valve plz fix

**Comment by iamthesenate-69** [comment]
@EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay @EatTofuEveryDay

**Comment by dthusian** [comment]
Can't Reproduce, nerd.
