### ISSUE TITLE
why cant i dronestike wat is this why cant i dronestike this is the worest thing since cgp grey animated with mouth @dthusian fix fix

### ISSUE THREAD

**Issue by iamthesenate-69** [dthusian/sasuke-prism#3]
dronestriking 2 guilds at once doesnt work 
![Screenshot (261)](https://user-images.githubusercontent.com/67884736/92987385-e9e7ba80-f48f-11ea-80b8-af391144c24f.png)
![Screenshot (261)](https://user-images.githubusercontent.com/67884736/92987389-ee13d800-f48f-11ea-9bd2-df32c92ef280.png)

fix fix i paid good money for this why does no work!!!!!!!!!!!!!!!!!!!!!!11111111111111111

**Comment by iamthesenate-69** [comment]
wait nvm it just takes 10 years

**Comment by iamthesenate-69** [comment]
how to close issue

**Comment by iamthesenate-69** [comment]
nvm i figre it out

**Comment by Multiapples** [comment]
bruh

**Comment by iamthesenate-69** [comment]
no u burh man
